Adds support for OpenSUSE/SLES/SLED, improves distribution detection.
joyent/sdc-vmtools pull request #5
Opened 2017-05-11 18:43 UTC by colstrom

2017-05-12 13:42 UTC, chorrell requested changes
Some formatting nits and one question about mixed caps in /etc/SuSE-release

2017-05-12 13:42 UTC, chorrell commented on src/linux/install-tools.sh
> +  if [[ -e /etc/rc.local ]]
This is a nice addition! However I'd prefer this to be consistent to how we typically format test blocks, e.g.,:

```
if [[ -e /etc/rc.local ]] ; then
```

2017-05-12 13:42 UTC, chorrell commented on src/linux/install-tools.sh
> +if [[ "$(uname -s)" != "Linux" ]]
Per previous comment, let's change this to 

```
if [[ "$(uname -s)" != "Linux" ]] ; then
```

2017-05-12 13:42 UTC, chorrell commented on src/linux/install-tools.sh
> +if [[ -f /etc/os-release ]]
See previous comment about formatting test block

2017-05-12 13:42 UTC, chorrell commented on src/linux/install-tools.sh
> +  elif [[ -f /etc/SuSE-release ]]
I'm not too familiar with SUSE, but is this file really in mixed caps?

2017-05-12 13:42 UTC, chorrell commented on src/linux/install-tools.sh
> +  done
This formatting would be preferable:

for distribution in ${ID_LIKE} ${ID}; do
    case ${distribution} in
      debian|ubuntu)
        method=debian
        ;;
      fedora|centos|rhel)
        method=redhat
        ;;
      suse|opensuse|sles|sled)
        method=suse
        ;;
    esac
done

2017-05-12 13:42 UTC, chorrell commented on src/linux/install-tools.sh
> +  if [[ -n "${method}" ]]
See previous comment about test/if blocks

2017-05-12 13:42 UTC, chorrell commented on src/linux/install-tools.sh
> +  if [[ -f /etc/redhat-release ]]
See previous comment about test/if blocks

2017-05-12 13:42 UTC, chorrell commented on src/linux/install-tools.sh
> +  elif [[ -f /etc/debian_version ]]
See previous comment about test/if blocks

2017-05-12 13:42 UTC, chorrell commented on src/linux/install-tools.sh
> +  elif [[ -f /etc/SuSE-release ]]
See previous comment about test/if blocks

2017-05-14 00:23 UTC, colstrom commented on src/linux/install-tools.sh
> +  if [[ -e /etc/rc.local ]]
Gotcha. I'll amend my patch accordingly.

2017-05-14 00:24 UTC, colstrom commented on src/linux/install-tools.sh
> +  done
Mmm, was that meant to format differently? I'd expect indentation within the `case`, no?

2017-05-14 00:29 UTC, colstrom commented on src/linux/install-tools.sh
> +  elif [[ -f /etc/SuSE-release ]]
I did a double-take when I saw it too, but it is correct (verified on SLES 12):
```
 $ ls -l /etc/S*
-rw-r--r--   1 root     root           17 Oct 25  2016 /etc/SUSE-brand
-rw-r--r--   1 root     root           46 Apr  1 15:05 /etc/SUSEConnect
-rw-r--r--   1 root     root          377 Mar  6 02:06 /etc/SUSEConnect.example
-rw-r--r--   1 root     root          215 Oct 25  2016 /etc/SuSE-release
```

2017-05-15 14:06 UTC, chorrell commented on src/linux/install-tools.sh
> +  done
Yes, correct, this was a markdown formatting issue on my part.

2017-05-15 14:06 UTC, chorrell approved these changes

2017-05-15 14:06 UTC, chorrell commented
LGTM

2017-05-15 14:06 UTC, merged