IMAGE-1181 hybrid images could be built in a zone
joyent/sdc-vmtools pull request #8
Opened 2019-11-01 22:17 UTC by mgerdts

2019-11-12 17:43 UTC, timfoster requested changes
With some minor nits mentioned below, I _think_ this is mostly fine.

I was able to create an image using these bits, could create a VM with it, though starting and connecting to the VMs vnc port just gave me a blank screen (maybe I was supposed to do something special for tty/console redirection during the install?)

2019-11-12 17:43 UTC, timfoster commented on bin/create-hybrid-image
> +		echo "  zonecfg -z $(zonename) 'add fs; set type=lofs; set dir=/smartdc set special=/smartdc; set options=ro; end'" 1>&2
Trying this I got:
```
[root@kura ~]#   zonecfg -z 3923c435-8688-47bb-a5f1-b213b010f825 'add fs; set type=lofs; set dir=/smartdc set special=/smartdc; set options=ro; end'
syntax error at 'set'
Commands:

add <resource-type>
	(global scope)
add <property-name> <property-value>
	(resource scope)
cancel
clear <property-name>
commit
create [-F] [ -a <path> | -b | -t <template> ]
delete [-F]
end
exit [-F]
export [-f output-file]
help [commands] [syntax] [usage] [<command-name>]
info [<resource-type> [property-name=property-value]*]
remove [-F] <resource-type> [ <property-name>=<property-value> ]*
	(global scope)
remove [-F] <property-name> <property-value>
	(resource scope)
revert [-F]
select <resource-type> { <property-name>=<property-value> }
set <property-name>=<property-value>
verify
Assertion failed: num_unclaimed_tokens == 0, file zonecfg_lex.l, line 438
Abort (core dumped)
[root@kura ~]#
```

It looks like we're missing a semi-colon in "set dir=/smartdc set special=/smartdc"

2019-11-12 17:43 UTC, timfoster commented on bin/create-hybrid-image
> +		echo "Fix by running the following in the global zone:" 1>&2
We probably should mention that the VM has to be rebooted for this to take effect? (or is there some other 'zoneadm -z zone apply'-like command we could suggest instead?)

2019-11-12 17:43 UTC, timfoster commented on bin/create-hybrid-image
> +	#   pwait $(cat /tmp/vm.pid)
I think we need pfexec cat /tmp/vm.pid or we need to chmod the pid file after creation, otherwise:
```
timf@jenkins-agent-multiarch-15.4.1 (IMAGE-1181) ./bin/create-hybrid-image  -i debian-9.4.0-amd64-netinst.iso  -n timf-debian -d "some text" -u http://bar.com
*** Starting image creation process! ***
==> Creating blank timf-debian virtual disk...done!
==>
==> Starting timf-debian with cdrom=debian-9.4.0-amd64-netinst.iso:
==>
==> Getting VNC info for timf-debian:
==> Host:
==> Port: 5901
==>
==> Waiting for 'timf-debian' VM to stop...cat: /tmp/vm.pid: Permission denied
usage:  pwait [-v] pid ...
  (wait for processes to terminate)
  -v: verbose; report terminations to standard out
==> Cleaning up:
cannot destroy 'zones/3923c435-8688-47bb-a5f1-b213b010f825/data/vm/timf-debian.793f6414-c34b-c6e7-cfcf-ae8c689e53f7.disk0': dataset is busy
cannot destroy 'zones/3923c435-8688-47bb-a5f1-b213b010f825/data/vm/timf-debian.793f6414-c34b-c6e7-cfcf-ae8c689e53f7.disk0': dataset is busy
timf@jenkins-agent-multiarch-15.4.1 (IMAGE-1181)
```

2019-11-12 17:43 UTC, timfoster commented on bin/create-hybrid-image
> +	host=$(pfexec mdata-get sdc:nics |
I wonder should we fallback if there's no host information here - even emitting ifconfig -a would be better than nothing. On my SmartOS box, the sdc:nics mdata won't be there of course..

```
timf@jenkins-agent-multiarch-15.4.1 pfexec mdata-get sdc:nics | json -c 'this.nic_tag == "external"' -a ip
timf@jenkins-agent-multiarch-15.4.1 ifconfig
lo0: flags=2001000849<UP,LOOPBACK,RUNNING,MULTICAST,IPv4,VIRTUAL> mtu 8232 index 1
	inet 127.0.0.1 netmask ff000000
net0: flags=1004843<UP,BROADCAST,RUNNING,MULTICAST,DHCP,IPv4> mtu 1500 index 2
	inet 10.0.0.25 netmask ffffff00 broadcast 10.0.0.255
lo0: flags=2002000849<UP,LOOPBACK,RUNNING,MULTICAST,IPv6,VIRTUAL> mtu 8252 index 1
	inet6 ::1/128
timf@jenkins-agent-multiarch-15.4.1
```

2019-11-12 17:43 UTC, timfoster commented on bin/sdc-vmmanifest
> +#now=$(date -u +%Y-%m-%dT%H:%MZ)
Are these debug comments here to specify a different date format still needed?

2019-11-12 17:43 UTC, timfoster commented on bin/sdc-vmmanifest
> +# Copyright (c) 2011 Joyent Inc., All rights reserved.
Is this an old script or should we correct the copyright comment?

2019-11-12 17:50 UTC, timfoster commented
Aha, creating a `kvm` rather than `bhyve` vm worked with my test image.

2019-11-13 16:12 UTC, mgerdts commented
> I was able to create an image using these bits, could create a VM with it, though starting and connecting to the VMs vnc port just gave me a blank screen (maybe I was supposed to do something special for tty/console redirection during the install?)

bhyve does not support vga bios, so these hybrid images will not have proper vnc support with bhyve.  If we created bhyve-only images with uefi boot, vnc would be supported.

Strictly speaking, it would be possible to generate images that can boot from bios or uefi bootroms.  AFAICT, this would require a fair amount of hackcraft to get it right in the image and is unlikely to be properly maintained as the boot loader and/or kernel are patched.

The bhyve vnc implementation is lackluster enough that there is little sense in making a special effort to support uefi boot.

2019-11-13 16:16 UTC, mgerdts commented on bin/create-hybrid-image
> +		echo "  zonecfg -z $(zonename) 'add fs; set type=lofs; set dir=/smartdc set special=/smartdc; set options=ro; end'" 1>&2
ok

2019-11-13 16:18 UTC, mgerdts commented on bin/create-hybrid-image
> +		echo "Fix by running the following in the global zone:" 1>&2
alas, no `zoneadm apply`.  Will add a reboot suggestion.

2019-11-13 16:20 UTC, mgerdts commented on bin/create-hybrid-image
> +	#   pwait $(cat /tmp/vm.pid)
yep, hit that in follow-up work as well.

2019-11-13 16:27 UTC, mgerdts commented on bin/create-hybrid-image
> +	host=$(pfexec mdata-get sdc:nics |
I'll rework this to give a line per ip:port, making it more copypasta friendly.

2019-11-13 16:28 UTC, mgerdts commented on bin/sdc-vmmanifest
> +#now=$(date -u +%Y-%m-%dT%H:%MZ)
This file was just moved from a different repo with no changes.

2019-11-13 16:28 UTC, mgerdts commented on bin/sdc-vmmanifest
> +# Copyright (c) 2011 Joyent Inc., All rights reserved.
This file was just moved from a different repo with no changes.

2019-11-13 19:51 UTC, mgerdts commented
I've updated this to address @timfoster 's feedback as well as some other issues I found while creating mi-centos-hvm (for all centos hybrid images).  Per our discussion, these scripts will be added to eng instead of sdc-vmtools.  This PR will be abandoned.

2019-12-02 16:17 UTC, mgerdts commented
This has been superseded by https://github.com/joyent/eng/pull/22

2019-12-02 16:17 UTC, closed without merging